
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServiceSoapImpl", targetNamespace = "http://ws.hd.saifdine.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoapImpl {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.GetComptesResponse")
    @Action(input = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesRequest", output = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteRequest", output = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://ws.hd.saifdine.ma/", className = "proxy.ConversionResponse")
    @Action(input = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionRequest", output = "http://ws.hd.saifdine.ma/WebServiceSoapImpl/conversionResponse")
    public double conversion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
