
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceSoapImplService", targetNamespace = "http://ws.hd.saifdine.ma/", wsdlLocation = "http://localhost:8080/ws/compte?wsdl")
public class WebServiceSoapImplService
    extends Service
{

    private static final URL WEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException WEBSERVICESOAPIMPLSERVICE_EXCEPTION;
    private static final QName WEBSERVICESOAPIMPLSERVICE_QNAME = new QName("http://ws.hd.saifdine.ma/", "WebServiceSoapImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/compte?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceSoapImplService() {
        super(__getWsdlLocation(), WEBSERVICESOAPIMPLSERVICE_QNAME);
    }

    public WebServiceSoapImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public WebServiceSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESOAPIMPLSERVICE_QNAME);
    }

    public WebServiceSoapImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public WebServiceSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceSoapImpl
     */
    @WebEndpoint(name = "WebServiceSoapImplPort")
    public WebServiceSoapImpl getWebServiceSoapImplPort() {
        return super.getPort(new QName("http://ws.hd.saifdine.ma/", "WebServiceSoapImplPort"), WebServiceSoapImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSoapImpl
     */
    @WebEndpoint(name = "WebServiceSoapImplPort")
    public WebServiceSoapImpl getWebServiceSoapImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.hd.saifdine.ma/", "WebServiceSoapImplPort"), WebServiceSoapImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESOAPIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
